# Generated by Django 4.2.27 on 2025-12-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ИИН сотрудника')),
                ('device_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название устройства/камеры')),
                ('event_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время события')),
                ('picture_data', models.TextField(blank=True, null=True, verbose_name='Фото в формате Base64')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Сырые данные события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Событие камеры',
                'verbose_name_plural': 'События камер',
                'ordering': ['-event_time', '-created_at'],
                'indexes': [models.Index(fields=['employee_no', 'event_time'], name='camera_even_employe_a8a63f_idx'), models.Index(fields=['device_name', 'event_time'], name='camera_even_device__9563d0_idx')],
            },
        ),
    ]
