# Generated by Django 4.2.27 on 2025-12-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cameraevent',
            name='camera_even_employe_a8a63f_idx',
        ),
        migrations.RemoveField(
            model_name='cameraevent',
            name='employee_no',
        ),
        migrations.AddField(
            model_name='cameraevent',
            name='hikvision_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID от Hikvision'),
        ),
        migrations.AddIndex(
            model_name='cameraevent',
            index=models.Index(fields=['hikvision_id', 'event_time'], name='camera_even_hikvisi_08cbc5_idx'),
        ),
    ]
