# Generated by Django 4.2.27 on 2025-12-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_events', '0002_remove_cameraevent_camera_even_employe_a8a63f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hikvision_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID от Hikvision')),
                ('entry_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время входа')),
                ('exit_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время выхода')),
                ('device_name_entry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Устройство входа')),
                ('device_name_exit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Устройство выхода')),
                ('work_duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Продолжительность работы (секунды)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Запись входа/выхода',
                'verbose_name_plural': 'Записи входов/выходов',
                'ordering': ['-entry_time'],
                'indexes': [models.Index(fields=['hikvision_id', 'entry_time'], name='camera_even_hikvisi_3006db_idx'), models.Index(fields=['entry_time'], name='camera_even_entry_t_bc0e57_idx'), models.Index(fields=['exit_time'], name='camera_even_exit_ti_76bbd1_idx')],
            },
        ),
    ]
