# Generated by Django 6.0 on 2025-12-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_events', '0003_entryexit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hikvision_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID от Hikvision')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подразделение')),
                ('card_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер карты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['hikvision_id'],
                'indexes': [models.Index(fields=['hikvision_id'], name='camera_even_hikvisi_0156de_idx'), models.Index(fields=['department'], name='camera_even_departm_bc606e_idx')],
            },
        ),
    ]
