# Generated by Django 6.0 on 2025-12-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera_events', '0005_department_and_update_employee'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='department',
            new_name='camera_even_name_fd4a33_idx',
            old_name='camera_even_name_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='camera_even_parent__57a782_idx',
            old_name='camera_even_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='camera_even_departm_88c763_idx',
            old_name='camera_even_departm_new_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='camera_even_departm_b3f09d_idx',
            old_name='camera_even_departm_old_idx',
        ),
    ]
