# Generated by Django 6.0 on 2025-12-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_events', '0006_rename_camera_even_name_idx_camera_even_name_fd4a33_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('regular', 'Обычный график'), ('floating', 'Плавающий график'), ('round_the_clock', 'Круглосуточный')], db_index=True, default='regular', max_length=20, verbose_name='Тип графика')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='Список дней недели (0=Понедельник, 6=Воскресенье)', verbose_name='Дни недели')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала работы')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания работы')),
                ('floating_shifts', models.JSONField(blank=True, default=list, help_text='Список смен для плавающего графика', verbose_name='Плавающие смены')),
                ('description', models.TextField(blank=True, help_text="Текстовое описание графика (например: 'Пн-Пт 08:00-17:00' или 'Чередование день/ночь')", null=True, verbose_name='Описание графика')),
                ('allowed_late_minutes', models.IntegerField(default=0, help_text='На сколько минут можно опоздать (например: 15)', verbose_name='Допустимое опоздание (минуты)')),
                ('allowed_early_leave_minutes', models.IntegerField(default=0, help_text='На сколько минут можно уйти раньше (например: 15)', verbose_name='Допустимый ранний уход (минуты)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='camera_events.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'ordering': ['employee', 'schedule_type'],
                'indexes': [models.Index(fields=['employee', 'schedule_type'], name='camera_even_employe_9edad9_idx'), models.Index(fields=['schedule_type'], name='camera_even_schedul_0371e1_idx')],
            },
        ),
    ]
