# Generated by Django 6.0 on 2025-12-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_events', '0007_workschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryexit',
            name='early_leave_counted',
            field=models.BooleanField(db_index=True, default=False, help_text='Флаг, указывающий, был ли ранний уход учтен в статистике', verbose_name='Ранний уход учтен'),
        ),
        migrations.AddField(
            model_name='entryexit',
            name='late_counted',
            field=models.BooleanField(db_index=True, default=False, help_text='Флаг, указывающий, было ли опоздание учтено в статистике', verbose_name='Опоздание учтено'),
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_count', models.IntegerField(default=0, help_text='Общее количество опозданий сотрудника', verbose_name='Количество опозданий')),
                ('early_leave_count', models.IntegerField(default=0, help_text='Общее количество ранних уходов и недоработок', verbose_name='Количество ранних уходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to='camera_events.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Статистика посещаемости',
                'verbose_name_plural': 'Статистика посещаемости',
                'ordering': ['-late_count', '-early_leave_count'],
                'indexes': [models.Index(fields=['employee'], name='camera_even_employe_cf7971_idx')],
            },
        ),
    ]
