# Generated by Django 6.0 on 2025-12-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_events', '0008_entryexit_early_leave_counted_entryexit_late_counted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, help_text='Должность сотрудника', max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
