# Generated by Django 6.0 on 2025-12-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_events', '0009_add_position_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_time', models.DateTimeField(db_index=True, verbose_name='Фактическое время начала')),
                ('actual_end_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Фактическое время окончания')),
                ('scheduled_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Плановое время начала')),
                ('scheduled_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Плановое время окончания')),
                ('is_late', models.BooleanField(db_index=True, default=False, help_text='Сотрудник опоздал на работу', verbose_name='Опоздание')),
                ('is_early_leave', models.BooleanField(db_index=True, default=False, help_text='Сотрудник ушел раньше времени', verbose_name='Ранний уход')),
                ('crosses_midnight', models.BooleanField(default=False, help_text='Смена пересекает полночь', verbose_name='Смена через полночь')),
                ('is_extra_shift', models.BooleanField(default=False, help_text='Смена вне расписания', verbose_name='Дополнительная смена')),
                ('anomalies', models.JSONField(blank=True, default=list, help_text='Список обнаруженных аномалий', verbose_name='Аномалии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='camera_events.employee', verbose_name='Сотрудник')),
                ('entry_exit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_record', to='camera_events.entryexit', verbose_name='Запись входа/выхода')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='camera_events.workschedule', verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Запись посещаемости',
                'verbose_name_plural': 'Записи посещаемости',
                'ordering': ['-actual_start_time'],
                'indexes': [models.Index(fields=['employee', 'actual_start_time'], name='camera_even_employe_5bb1fa_idx'), models.Index(fields=['is_late', 'is_early_leave'], name='camera_even_is_late_0641ac_idx'), models.Index(fields=['crosses_midnight'], name='camera_even_crosses_44a843_idx')],
            },
        ),
    ]
